/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using kern.services.EaseeClient.Client;
using kern.services.EaseeClient.Api;
// uncomment below to import models
//using kern.services.EaseeClient.Model;

namespace kern.services.EaseeClient.Test.Api
{
    /// <summary>
    ///  Class for testing ConsumptionApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConsumptionApiTests : IDisposable
    {
        private ConsumptionApi instance;

        public ConsumptionApiTests()
        {
            instance = new ConsumptionApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsumptionApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConsumptionApi
            //Assert.IsType<ConsumptionApi>(instance);
        }

        /// <summary>
        /// Test ApiConsumptionTotalGet
        /// </summary>
        [Fact]
        public void ApiConsumptionTotalGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string>? chargerIds = null;
            //DateTime? fromDateTimeUtc = null;
            //DateTime? toDateTimeUtc = null;
            //EaseeBusinessLayerManagersTotalConsumptionTotalConsumptionAggregationType? grouping = null;
            //string? tz = null;
            //var response = instance.ApiConsumptionTotalGet(chargerIds, fromDateTimeUtc, toDateTimeUtc, grouping, tz);
            //Assert.IsType<List<EaseeBusinessLayerManagersTotalConsumptionTotalConsumptionPeriod>>(response);
        }
    }
}
