/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeAccessControlModelsSitePermissionRequestDTO
    /// </summary>
    [DataContract(Name = "Easee.AccessControl.Models.SitePermissionRequestDTO")]
    public partial class EaseeAccessControlModelsSitePermissionRequestDTO : IEquatable<EaseeAccessControlModelsSitePermissionRequestDTO>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets SiteUserRole
        /// </summary>
        [DataMember(Name = "siteUserRole", EmitDefaultValue = false)]
        public EaseeCoreEnumsSiteUserRole? SiteUserRole { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeAccessControlModelsSitePermissionRequestDTO" /> class.
        /// </summary>
        /// <param name="phoneNo">phoneNo.</param>
        /// <param name="siteUserRole">siteUserRole.</param>
        public EaseeAccessControlModelsSitePermissionRequestDTO(string phoneNo = default(string), EaseeCoreEnumsSiteUserRole? siteUserRole = default(EaseeCoreEnumsSiteUserRole?))
        {
            this.PhoneNo = phoneNo;
            this.SiteUserRole = siteUserRole;
        }

        /// <summary>
        /// Gets or Sets PhoneNo
        /// </summary>
        [DataMember(Name = "phoneNo", EmitDefaultValue = true)]
        public string PhoneNo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeAccessControlModelsSitePermissionRequestDTO {\n");
            sb.Append("  PhoneNo: ").Append(PhoneNo).Append("\n");
            sb.Append("  SiteUserRole: ").Append(SiteUserRole).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeAccessControlModelsSitePermissionRequestDTO);
        }

        /// <summary>
        /// Returns true if EaseeAccessControlModelsSitePermissionRequestDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeAccessControlModelsSitePermissionRequestDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeAccessControlModelsSitePermissionRequestDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PhoneNo == input.PhoneNo ||
                    (this.PhoneNo != null &&
                    this.PhoneNo.Equals(input.PhoneNo))
                ) && 
                (
                    this.SiteUserRole == input.SiteUserRole ||
                    this.SiteUserRole.Equals(input.SiteUserRole)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PhoneNo != null)
                {
                    hashCode = (hashCode * 59) + this.PhoneNo.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.SiteUserRole.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
