/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeUserAdministrationDomainDTOSitePermissionDTO
    /// </summary>
    [DataContract(Name = "Easee.UserAdministration.Domain.DTO.SitePermissionDTO")]
    public partial class EaseeUserAdministrationDomainDTOSitePermissionDTO : IEquatable<EaseeUserAdministrationDomainDTOSitePermissionDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeUserAdministrationDomainDTOSitePermissionDTO" /> class.
        /// </summary>
        /// <param name="isOwner">isOwner.</param>
        /// <param name="siteUsers">siteUsers.</param>
        public EaseeUserAdministrationDomainDTOSitePermissionDTO(bool isOwner = default(bool), List<EaseeUserAdministrationDomainDTOSiteUserDTO> siteUsers = default(List<EaseeUserAdministrationDomainDTOSiteUserDTO>))
        {
            this.IsOwner = isOwner;
            this.SiteUsers = siteUsers;
        }

        /// <summary>
        /// Gets or Sets IsOwner
        /// </summary>
        [DataMember(Name = "isOwner", EmitDefaultValue = true)]
        public bool IsOwner { get; set; }

        /// <summary>
        /// Gets or Sets SiteUsers
        /// </summary>
        [DataMember(Name = "siteUsers", EmitDefaultValue = true)]
        public List<EaseeUserAdministrationDomainDTOSiteUserDTO> SiteUsers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeUserAdministrationDomainDTOSitePermissionDTO {\n");
            sb.Append("  IsOwner: ").Append(IsOwner).Append("\n");
            sb.Append("  SiteUsers: ").Append(SiteUsers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeUserAdministrationDomainDTOSitePermissionDTO);
        }

        /// <summary>
        /// Returns true if EaseeUserAdministrationDomainDTOSitePermissionDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeUserAdministrationDomainDTOSitePermissionDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeUserAdministrationDomainDTOSitePermissionDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.IsOwner == input.IsOwner ||
                    this.IsOwner.Equals(input.IsOwner)
                ) && 
                (
                    this.SiteUsers == input.SiteUsers ||
                    this.SiteUsers != null &&
                    input.SiteUsers != null &&
                    this.SiteUsers.SequenceEqual(input.SiteUsers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.IsOwner.GetHashCode();
                if (this.SiteUsers != null)
                {
                    hashCode = (hashCode * 59) + this.SiteUsers.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
