/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeBusinessLayerManagersTotalConsumptionChargerConsumption
    /// </summary>
    [DataContract(Name = "Easee.BusinessLayer.Managers.TotalConsumption.ChargerConsumption")]
    public partial class EaseeBusinessLayerManagersTotalConsumptionChargerConsumption : IEquatable<EaseeBusinessLayerManagersTotalConsumptionChargerConsumption>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeBusinessLayerManagersTotalConsumptionChargerConsumption" /> class.
        /// </summary>
        /// <param name="chargerId">chargerId.</param>
        /// <param name="consumption">consumption.</param>
        public EaseeBusinessLayerManagersTotalConsumptionChargerConsumption(string chargerId = default(string), double consumption = default(double))
        {
            this.ChargerId = chargerId;
            this.Consumption = consumption;
        }

        /// <summary>
        /// Gets or Sets ChargerId
        /// </summary>
        [DataMember(Name = "chargerId", EmitDefaultValue = true)]
        public string ChargerId { get; set; }

        /// <summary>
        /// Gets or Sets Consumption
        /// </summary>
        [DataMember(Name = "consumption", EmitDefaultValue = false)]
        public double Consumption { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeBusinessLayerManagersTotalConsumptionChargerConsumption {\n");
            sb.Append("  ChargerId: ").Append(ChargerId).Append("\n");
            sb.Append("  Consumption: ").Append(Consumption).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeBusinessLayerManagersTotalConsumptionChargerConsumption);
        }

        /// <summary>
        /// Returns true if EaseeBusinessLayerManagersTotalConsumptionChargerConsumption instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeBusinessLayerManagersTotalConsumptionChargerConsumption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeBusinessLayerManagersTotalConsumptionChargerConsumption input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ChargerId == input.ChargerId ||
                    (this.ChargerId != null &&
                    this.ChargerId.Equals(input.ChargerId))
                ) && 
                (
                    this.Consumption == input.Consumption ||
                    this.Consumption.Equals(input.Consumption)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChargerId != null)
                {
                    hashCode = (hashCode * 59) + this.ChargerId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Consumption.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
