/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeServicesLifetimeEnergyReportingMeasurement
    /// </summary>
    [DataContract(Name = "Easee.Services.LifetimeEnergyReporting.Measurement")]
    public partial class EaseeServicesLifetimeEnergyReportingMeasurement : IEquatable<EaseeServicesLifetimeEnergyReportingMeasurement>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeServicesLifetimeEnergyReportingMeasurement" /> class.
        /// </summary>
        /// <param name="value">value.</param>
        /// <param name="measuredAt">measuredAt.</param>
        public EaseeServicesLifetimeEnergyReportingMeasurement(double value = default(double), DateTime measuredAt = default(DateTime))
        {
            this.Value = value;
            this.MeasuredAt = measuredAt;
        }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public double Value { get; set; }

        /// <summary>
        /// Gets or Sets MeasuredAt
        /// </summary>
        [DataMember(Name = "measuredAt", EmitDefaultValue = false)]
        public DateTime MeasuredAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeServicesLifetimeEnergyReportingMeasurement {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  MeasuredAt: ").Append(MeasuredAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeServicesLifetimeEnergyReportingMeasurement);
        }

        /// <summary>
        /// Returns true if EaseeServicesLifetimeEnergyReportingMeasurement instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeServicesLifetimeEnergyReportingMeasurement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeServicesLifetimeEnergyReportingMeasurement input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Value == input.Value ||
                    this.Value.Equals(input.Value)
                ) && 
                (
                    this.MeasuredAt == input.MeasuredAt ||
                    (this.MeasuredAt != null &&
                    this.MeasuredAt.Equals(input.MeasuredAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Value.GetHashCode();
                if (this.MeasuredAt != null)
                {
                    hashCode = (hashCode * 59) + this.MeasuredAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
