/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsDashboardDashboardChargerState
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Dashboard.DashboardChargerState")]
    public partial class EaseeCoreDTOsDashboardDashboardChargerState : IEquatable<EaseeCoreDTOsDashboardDashboardChargerState>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsDashboardDashboardChargerState" /> class.
        /// </summary>
        /// <param name="chargerID">chargerID.</param>
        /// <param name="chargerConfig">chargerConfig.</param>
        /// <param name="chargerState">chargerState.</param>
        public EaseeCoreDTOsDashboardDashboardChargerState(string chargerID = default(string), EaseeCoreDTOsChargerChargerConfigurationDTO chargerConfig = default(EaseeCoreDTOsChargerChargerConfigurationDTO), EaseeCoreDTOsChargerChargerStateDTO chargerState = default(EaseeCoreDTOsChargerChargerStateDTO))
        {
            this.ChargerID = chargerID;
            this.ChargerConfig = chargerConfig;
            this.ChargerState = chargerState;
        }

        /// <summary>
        /// Gets or Sets ChargerID
        /// </summary>
        [DataMember(Name = "chargerID", EmitDefaultValue = true)]
        public string ChargerID { get; set; }

        /// <summary>
        /// Gets or Sets ChargerConfig
        /// </summary>
        [DataMember(Name = "chargerConfig", EmitDefaultValue = false)]
        public EaseeCoreDTOsChargerChargerConfigurationDTO ChargerConfig { get; set; }

        /// <summary>
        /// Gets or Sets ChargerState
        /// </summary>
        [DataMember(Name = "chargerState", EmitDefaultValue = false)]
        public EaseeCoreDTOsChargerChargerStateDTO ChargerState { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsDashboardDashboardChargerState {\n");
            sb.Append("  ChargerID: ").Append(ChargerID).Append("\n");
            sb.Append("  ChargerConfig: ").Append(ChargerConfig).Append("\n");
            sb.Append("  ChargerState: ").Append(ChargerState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsDashboardDashboardChargerState);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsDashboardDashboardChargerState instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsDashboardDashboardChargerState to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsDashboardDashboardChargerState input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ChargerID == input.ChargerID ||
                    (this.ChargerID != null &&
                    this.ChargerID.Equals(input.ChargerID))
                ) && 
                (
                    this.ChargerConfig == input.ChargerConfig ||
                    (this.ChargerConfig != null &&
                    this.ChargerConfig.Equals(input.ChargerConfig))
                ) && 
                (
                    this.ChargerState == input.ChargerState ||
                    (this.ChargerState != null &&
                    this.ChargerState.Equals(input.ChargerState))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChargerID != null)
                {
                    hashCode = (hashCode * 59) + this.ChargerID.GetHashCode();
                }
                if (this.ChargerConfig != null)
                {
                    hashCode = (hashCode * 59) + this.ChargerConfig.GetHashCode();
                }
                if (this.ChargerState != null)
                {
                    hashCode = (hashCode * 59) + this.ChargerState.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
