/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsEqualizerDeviceModeDTO
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Equalizer.DeviceModeDTO")]
    public partial class EaseeCoreDTOsEqualizerDeviceModeDTO : IEquatable<EaseeCoreDTOsEqualizerDeviceModeDTO>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets ActiveMode
        /// </summary>
        [DataMember(Name = "activeMode", EmitDefaultValue = false)]
        public EaseeCoreEnumsDeviceMode? ActiveMode { get; set; }

        /// <summary>
        /// Gets or Sets ConfiguredMode
        /// </summary>
        [DataMember(Name = "configuredMode", EmitDefaultValue = false)]
        public EaseeCoreEnumsDeviceMode? ConfiguredMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsEqualizerDeviceModeDTO" /> class.
        /// </summary>
        /// <param name="activeMode">activeMode.</param>
        /// <param name="configuredMode">configuredMode.</param>
        public EaseeCoreDTOsEqualizerDeviceModeDTO(EaseeCoreEnumsDeviceMode? activeMode = default(EaseeCoreEnumsDeviceMode?), EaseeCoreEnumsDeviceMode? configuredMode = default(EaseeCoreEnumsDeviceMode?))
        {
            this.ActiveMode = activeMode;
            this.ConfiguredMode = configuredMode;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsEqualizerDeviceModeDTO {\n");
            sb.Append("  ActiveMode: ").Append(ActiveMode).Append("\n");
            sb.Append("  ConfiguredMode: ").Append(ConfiguredMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsEqualizerDeviceModeDTO);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsEqualizerDeviceModeDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsEqualizerDeviceModeDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsEqualizerDeviceModeDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ActiveMode == input.ActiveMode ||
                    this.ActiveMode.Equals(input.ActiveMode)
                ) && 
                (
                    this.ConfiguredMode == input.ConfiguredMode ||
                    this.ConfiguredMode.Equals(input.ConfiguredMode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ActiveMode.GetHashCode();
                hashCode = (hashCode * 59) + this.ConfiguredMode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
