/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsSessionAuthorizationTokenEnergy
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Session.AuthorizationTokenEnergy")]
    public partial class EaseeCoreDTOsSessionAuthorizationTokenEnergy : IEquatable<EaseeCoreDTOsSessionAuthorizationTokenEnergy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsSessionAuthorizationTokenEnergy" /> class.
        /// </summary>
        /// <param name="rfidKey">rfidKey.</param>
        /// <param name="energy">energy.</param>
        public EaseeCoreDTOsSessionAuthorizationTokenEnergy(string rfidKey = default(string), double energy = default(double))
        {
            this.RfidKey = rfidKey;
            this.Energy = energy;
        }

        /// <summary>
        /// Gets or Sets RfidKey
        /// </summary>
        [DataMember(Name = "rfidKey", EmitDefaultValue = true)]
        public string RfidKey { get; set; }

        /// <summary>
        /// Gets or Sets Energy
        /// </summary>
        [DataMember(Name = "energy", EmitDefaultValue = false)]
        public double Energy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsSessionAuthorizationTokenEnergy {\n");
            sb.Append("  RfidKey: ").Append(RfidKey).Append("\n");
            sb.Append("  Energy: ").Append(Energy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsSessionAuthorizationTokenEnergy);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsSessionAuthorizationTokenEnergy instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsSessionAuthorizationTokenEnergy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsSessionAuthorizationTokenEnergy input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.RfidKey == input.RfidKey ||
                    (this.RfidKey != null &&
                    this.RfidKey.Equals(input.RfidKey))
                ) && 
                (
                    this.Energy == input.Energy ||
                    this.Energy.Equals(input.Energy)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RfidKey != null)
                {
                    hashCode = (hashCode * 59) + this.RfidKey.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Energy.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
