/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsSessionYearlySessionSummaryDTO
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Session.YearlySessionSummaryDTO")]
    public partial class EaseeCoreDTOsSessionYearlySessionSummaryDTO : IEquatable<EaseeCoreDTOsSessionYearlySessionSummaryDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsSessionYearlySessionSummaryDTO" /> class.
        /// </summary>
        /// <param name="year">year.</param>
        /// <param name="totalEnergyUsage">totalEnergyUsage.</param>
        public EaseeCoreDTOsSessionYearlySessionSummaryDTO(int year = default(int), double totalEnergyUsage = default(double))
        {
            this.Year = year;
            this.TotalEnergyUsage = totalEnergyUsage;
        }

        /// <summary>
        /// Gets or Sets Year
        /// </summary>
        [DataMember(Name = "year", EmitDefaultValue = false)]
        public int Year { get; set; }

        /// <summary>
        /// Gets or Sets TotalEnergyUsage
        /// </summary>
        [DataMember(Name = "totalEnergyUsage", EmitDefaultValue = false)]
        public double TotalEnergyUsage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsSessionYearlySessionSummaryDTO {\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  TotalEnergyUsage: ").Append(TotalEnergyUsage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsSessionYearlySessionSummaryDTO);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsSessionYearlySessionSummaryDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsSessionYearlySessionSummaryDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsSessionYearlySessionSummaryDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Year == input.Year ||
                    this.Year.Equals(input.Year)
                ) && 
                (
                    this.TotalEnergyUsage == input.TotalEnergyUsage ||
                    this.TotalEnergyUsage.Equals(input.TotalEnergyUsage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Year.GetHashCode();
                hashCode = (hashCode * 59) + this.TotalEnergyUsage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
