/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// Defines Easee.Core.Enums.OutputPhaseType
    /// </summary>
    public enum EaseeCoreEnumsOutputPhaseType
    {
        /// <summary>
        /// Enum NUMBER_0 for value: 0
        /// </summary>
        NUMBER_0 = 0,

        /// <summary>
        /// Enum NUMBER_10 for value: 10
        /// </summary>
        NUMBER_10 = 10,

        /// <summary>
        /// Enum NUMBER_11 for value: 11
        /// </summary>
        NUMBER_11 = 11,

        /// <summary>
        /// Enum NUMBER_12 for value: 12
        /// </summary>
        NUMBER_12 = 12,

        /// <summary>
        /// Enum NUMBER_13 for value: 13
        /// </summary>
        NUMBER_13 = 13,

        /// <summary>
        /// Enum NUMBER_14 for value: 14
        /// </summary>
        NUMBER_14 = 14,

        /// <summary>
        /// Enum NUMBER_15 for value: 15
        /// </summary>
        NUMBER_15 = 15,

        /// <summary>
        /// Enum NUMBER_20 for value: 20
        /// </summary>
        NUMBER_20 = 20,

        /// <summary>
        /// Enum NUMBER_21 for value: 21
        /// </summary>
        NUMBER_21 = 21,

        /// <summary>
        /// Enum NUMBER_22 for value: 22
        /// </summary>
        NUMBER_22 = 22,

        /// <summary>
        /// Enum NUMBER_30 for value: 30
        /// </summary>
        NUMBER_30 = 30

    }

}
