/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsSiteChargerAccessDTO
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Site.ChargerAccessDTO")]
    public partial class EaseeCoreDTOsSiteChargerAccessDTO : IEquatable<EaseeCoreDTOsSiteChargerAccessDTO>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets LevelOfAccess
        /// </summary>
        [DataMember(Name = "levelOfAccess", EmitDefaultValue = false)]
        public EaseeCoreEnumsLevelOfAccess? LevelOfAccess { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsSiteChargerAccessDTO" /> class.
        /// </summary>
        /// <param name="chargerId">chargerId.</param>
        /// <param name="levelOfAccess">levelOfAccess.</param>
        public EaseeCoreDTOsSiteChargerAccessDTO(string chargerId = default(string), EaseeCoreEnumsLevelOfAccess? levelOfAccess = default(EaseeCoreEnumsLevelOfAccess?))
        {
            this.ChargerId = chargerId;
            this.LevelOfAccess = levelOfAccess;
        }

        /// <summary>
        /// Gets or Sets ChargerId
        /// </summary>
        [DataMember(Name = "chargerId", EmitDefaultValue = true)]
        public string ChargerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsSiteChargerAccessDTO {\n");
            sb.Append("  ChargerId: ").Append(ChargerId).Append("\n");
            sb.Append("  LevelOfAccess: ").Append(LevelOfAccess).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsSiteChargerAccessDTO);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsSiteChargerAccessDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsSiteChargerAccessDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsSiteChargerAccessDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ChargerId == input.ChargerId ||
                    (this.ChargerId != null &&
                    this.ChargerId.Equals(input.ChargerId))
                ) && 
                (
                    this.LevelOfAccess == input.LevelOfAccess ||
                    this.LevelOfAccess.Equals(input.LevelOfAccess)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChargerId != null)
                {
                    hashCode = (hashCode * 59) + this.ChargerId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.LevelOfAccess.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
