/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsSiteDetailSiteDTO
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Site.DetailSiteDTO")]
    public partial class EaseeCoreDTOsSiteDetailSiteDTO : IEquatable<EaseeCoreDTOsSiteDetailSiteDTO>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets LevelOfAccess
        /// </summary>
        [DataMember(Name = "levelOfAccess", EmitDefaultValue = false)]
        public EaseeCoreEnumsLevelOfAccess? LevelOfAccess { get; set; }

        /// <summary>
        /// Gets or Sets SiteType
        /// </summary>
        [DataMember(Name = "siteType", EmitDefaultValue = false)]
        public EaseeCoreConstantsProductType? SiteType { get; set; }

        /// <summary>
        /// Gets or Sets UserRole
        /// </summary>
        [DataMember(Name = "userRole", EmitDefaultValue = false)]
        public EaseeCoreEnumsSiteUserRole? UserRole { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsSiteDetailSiteDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="siteKey">siteKey.</param>
        /// <param name="name">name.</param>
        /// <param name="levelOfAccess">levelOfAccess.</param>
        /// <param name="address">address.</param>
        /// <param name="contactInfo">contactInfo.</param>
        /// <param name="costPerKWh">costPerKWh.</param>
        /// <param name="costPerKwhExcludeVat">costPerKwhExcludeVat.</param>
        /// <param name="vat">vat.</param>
        /// <param name="currencyId">currencyId.</param>
        /// <param name="siteType">siteType.</param>
        /// <param name="ratedCurrent">ratedCurrent.</param>
        /// <param name="partnerId">partnerId.</param>
        /// <param name="ownerPartnerId">ownerPartnerId.</param>
        /// <param name="useDynamicMaster">useDynamicMaster.</param>
        /// <param name="circuits">circuits.</param>
        /// <param name="equalizers">equalizers.</param>
        /// <param name="createdOn">createdOn.</param>
        /// <param name="updatedOn">updatedOn.</param>
        /// <param name="userRole">userRole.</param>
        public EaseeCoreDTOsSiteDetailSiteDTO(int id = default(int), string siteKey = default(string), string name = default(string), EaseeCoreEnumsLevelOfAccess? levelOfAccess = default(EaseeCoreEnumsLevelOfAccess?), EaseeCoreDTOsSiteAddressDTO address = default(EaseeCoreDTOsSiteAddressDTO), EaseeCoreDTOsSiteContactInfoDTO contactInfo = default(EaseeCoreDTOsSiteContactInfoDTO), double? costPerKWh = default(double?), double costPerKwhExcludeVat = default(double), double? vat = default(double?), string currencyId = default(string), EaseeCoreConstantsProductType? siteType = default(EaseeCoreConstantsProductType?), double ratedCurrent = default(double), int? partnerId = default(int?), int? ownerPartnerId = default(int?), bool useDynamicMaster = default(bool), List<EaseeCoreDTOsSiteCircuitDTO> circuits = default(List<EaseeCoreDTOsSiteCircuitDTO>), List<EaseeCoreDTOsEqualizerEqualizerDTO> equalizers = default(List<EaseeCoreDTOsEqualizerEqualizerDTO>), DateTime createdOn = default(DateTime), DateTime updatedOn = default(DateTime), EaseeCoreEnumsSiteUserRole? userRole = default(EaseeCoreEnumsSiteUserRole?))
        {
            this.Id = id;
            this.SiteKey = siteKey;
            this.Name = name;
            this.LevelOfAccess = levelOfAccess;
            this.Address = address;
            this.ContactInfo = contactInfo;
            this.CostPerKWh = costPerKWh;
            this.CostPerKwhExcludeVat = costPerKwhExcludeVat;
            this.Vat = vat;
            this.CurrencyId = currencyId;
            this.SiteType = siteType;
            this.RatedCurrent = ratedCurrent;
            this.PartnerId = partnerId;
            this.OwnerPartnerId = ownerPartnerId;
            this.UseDynamicMaster = useDynamicMaster;
            this.Circuits = circuits;
            this.Equalizers = equalizers;
            this.CreatedOn = createdOn;
            this.UpdatedOn = updatedOn;
            this.UserRole = userRole;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets SiteKey
        /// </summary>
        [DataMember(Name = "siteKey", EmitDefaultValue = true)]
        public string SiteKey { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name = "address", EmitDefaultValue = false)]
        public EaseeCoreDTOsSiteAddressDTO Address { get; set; }

        /// <summary>
        /// Gets or Sets ContactInfo
        /// </summary>
        [DataMember(Name = "contactInfo", EmitDefaultValue = false)]
        public EaseeCoreDTOsSiteContactInfoDTO ContactInfo { get; set; }

        /// <summary>
        /// Gets or Sets CostPerKWh
        /// </summary>
        [DataMember(Name = "costPerKWh", EmitDefaultValue = true)]
        public double? CostPerKWh { get; set; }

        /// <summary>
        /// Gets or Sets CostPerKwhExcludeVat
        /// </summary>
        [DataMember(Name = "costPerKwhExcludeVat", EmitDefaultValue = false)]
        public double CostPerKwhExcludeVat { get; set; }

        /// <summary>
        /// Gets or Sets Vat
        /// </summary>
        [DataMember(Name = "vat", EmitDefaultValue = true)]
        public double? Vat { get; set; }

        /// <summary>
        /// Gets or Sets CurrencyId
        /// </summary>
        [DataMember(Name = "currencyId", EmitDefaultValue = true)]
        public string CurrencyId { get; set; }

        /// <summary>
        /// Gets or Sets RatedCurrent
        /// </summary>
        [DataMember(Name = "ratedCurrent", EmitDefaultValue = false)]
        public double RatedCurrent { get; set; }

        /// <summary>
        /// Gets or Sets PartnerId
        /// </summary>
        [DataMember(Name = "partnerId", EmitDefaultValue = true)]
        public int? PartnerId { get; set; }

        /// <summary>
        /// Gets or Sets OwnerPartnerId
        /// </summary>
        [DataMember(Name = "ownerPartnerId", EmitDefaultValue = true)]
        public int? OwnerPartnerId { get; set; }

        /// <summary>
        /// Gets or Sets UseDynamicMaster
        /// </summary>
        [DataMember(Name = "useDynamicMaster", EmitDefaultValue = true)]
        public bool UseDynamicMaster { get; set; }

        /// <summary>
        /// Gets or Sets Circuits
        /// </summary>
        [DataMember(Name = "circuits", EmitDefaultValue = true)]
        public List<EaseeCoreDTOsSiteCircuitDTO> Circuits { get; set; }

        /// <summary>
        /// Gets or Sets Equalizers
        /// </summary>
        [DataMember(Name = "equalizers", EmitDefaultValue = true)]
        public List<EaseeCoreDTOsEqualizerEqualizerDTO> Equalizers { get; set; }

        /// <summary>
        /// Gets or Sets CreatedOn
        /// </summary>
        [DataMember(Name = "createdOn", EmitDefaultValue = false)]
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedOn
        /// </summary>
        [DataMember(Name = "updatedOn", EmitDefaultValue = false)]
        public DateTime UpdatedOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsSiteDetailSiteDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SiteKey: ").Append(SiteKey).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  LevelOfAccess: ").Append(LevelOfAccess).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  ContactInfo: ").Append(ContactInfo).Append("\n");
            sb.Append("  CostPerKWh: ").Append(CostPerKWh).Append("\n");
            sb.Append("  CostPerKwhExcludeVat: ").Append(CostPerKwhExcludeVat).Append("\n");
            sb.Append("  Vat: ").Append(Vat).Append("\n");
            sb.Append("  CurrencyId: ").Append(CurrencyId).Append("\n");
            sb.Append("  SiteType: ").Append(SiteType).Append("\n");
            sb.Append("  RatedCurrent: ").Append(RatedCurrent).Append("\n");
            sb.Append("  PartnerId: ").Append(PartnerId).Append("\n");
            sb.Append("  OwnerPartnerId: ").Append(OwnerPartnerId).Append("\n");
            sb.Append("  UseDynamicMaster: ").Append(UseDynamicMaster).Append("\n");
            sb.Append("  Circuits: ").Append(Circuits).Append("\n");
            sb.Append("  Equalizers: ").Append(Equalizers).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  UpdatedOn: ").Append(UpdatedOn).Append("\n");
            sb.Append("  UserRole: ").Append(UserRole).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsSiteDetailSiteDTO);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsSiteDetailSiteDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsSiteDetailSiteDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsSiteDetailSiteDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.SiteKey == input.SiteKey ||
                    (this.SiteKey != null &&
                    this.SiteKey.Equals(input.SiteKey))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.LevelOfAccess == input.LevelOfAccess ||
                    this.LevelOfAccess.Equals(input.LevelOfAccess)
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.ContactInfo == input.ContactInfo ||
                    (this.ContactInfo != null &&
                    this.ContactInfo.Equals(input.ContactInfo))
                ) && 
                (
                    this.CostPerKWh == input.CostPerKWh ||
                    (this.CostPerKWh != null &&
                    this.CostPerKWh.Equals(input.CostPerKWh))
                ) && 
                (
                    this.CostPerKwhExcludeVat == input.CostPerKwhExcludeVat ||
                    this.CostPerKwhExcludeVat.Equals(input.CostPerKwhExcludeVat)
                ) && 
                (
                    this.Vat == input.Vat ||
                    (this.Vat != null &&
                    this.Vat.Equals(input.Vat))
                ) && 
                (
                    this.CurrencyId == input.CurrencyId ||
                    (this.CurrencyId != null &&
                    this.CurrencyId.Equals(input.CurrencyId))
                ) && 
                (
                    this.SiteType == input.SiteType ||
                    this.SiteType.Equals(input.SiteType)
                ) && 
                (
                    this.RatedCurrent == input.RatedCurrent ||
                    this.RatedCurrent.Equals(input.RatedCurrent)
                ) && 
                (
                    this.PartnerId == input.PartnerId ||
                    (this.PartnerId != null &&
                    this.PartnerId.Equals(input.PartnerId))
                ) && 
                (
                    this.OwnerPartnerId == input.OwnerPartnerId ||
                    (this.OwnerPartnerId != null &&
                    this.OwnerPartnerId.Equals(input.OwnerPartnerId))
                ) && 
                (
                    this.UseDynamicMaster == input.UseDynamicMaster ||
                    this.UseDynamicMaster.Equals(input.UseDynamicMaster)
                ) && 
                (
                    this.Circuits == input.Circuits ||
                    this.Circuits != null &&
                    input.Circuits != null &&
                    this.Circuits.SequenceEqual(input.Circuits)
                ) && 
                (
                    this.Equalizers == input.Equalizers ||
                    this.Equalizers != null &&
                    input.Equalizers != null &&
                    this.Equalizers.SequenceEqual(input.Equalizers)
                ) && 
                (
                    this.CreatedOn == input.CreatedOn ||
                    (this.CreatedOn != null &&
                    this.CreatedOn.Equals(input.CreatedOn))
                ) && 
                (
                    this.UpdatedOn == input.UpdatedOn ||
                    (this.UpdatedOn != null &&
                    this.UpdatedOn.Equals(input.UpdatedOn))
                ) && 
                (
                    this.UserRole == input.UserRole ||
                    this.UserRole.Equals(input.UserRole)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.SiteKey != null)
                {
                    hashCode = (hashCode * 59) + this.SiteKey.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.LevelOfAccess.GetHashCode();
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                if (this.ContactInfo != null)
                {
                    hashCode = (hashCode * 59) + this.ContactInfo.GetHashCode();
                }
                if (this.CostPerKWh != null)
                {
                    hashCode = (hashCode * 59) + this.CostPerKWh.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.CostPerKwhExcludeVat.GetHashCode();
                if (this.Vat != null)
                {
                    hashCode = (hashCode * 59) + this.Vat.GetHashCode();
                }
                if (this.CurrencyId != null)
                {
                    hashCode = (hashCode * 59) + this.CurrencyId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.SiteType.GetHashCode();
                hashCode = (hashCode * 59) + this.RatedCurrent.GetHashCode();
                if (this.PartnerId != null)
                {
                    hashCode = (hashCode * 59) + this.PartnerId.GetHashCode();
                }
                if (this.OwnerPartnerId != null)
                {
                    hashCode = (hashCode * 59) + this.OwnerPartnerId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.UseDynamicMaster.GetHashCode();
                if (this.Circuits != null)
                {
                    hashCode = (hashCode * 59) + this.Circuits.GetHashCode();
                }
                if (this.Equalizers != null)
                {
                    hashCode = (hashCode * 59) + this.Equalizers.GetHashCode();
                }
                if (this.CreatedOn != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedOn.GetHashCode();
                }
                if (this.UpdatedOn != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedOn.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.UserRole.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
