/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsDashboardDashboardCircuitStateDTO
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Dashboard.DashboardCircuitStateDTO")]
    public partial class EaseeCoreDTOsDashboardDashboardCircuitStateDTO : IEquatable<EaseeCoreDTOsDashboardDashboardCircuitStateDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsDashboardDashboardCircuitStateDTO" /> class.
        /// </summary>
        /// <param name="circuit">circuit.</param>
        /// <param name="chargerStates">chargerStates.</param>
        public EaseeCoreDTOsDashboardDashboardCircuitStateDTO(EaseeCoreDTOsSiteCircuitDTO circuit = default(EaseeCoreDTOsSiteCircuitDTO), List<EaseeCoreDTOsDashboardDashboardChargerState> chargerStates = default(List<EaseeCoreDTOsDashboardDashboardChargerState>))
        {
            this.Circuit = circuit;
            this.ChargerStates = chargerStates;
        }

        /// <summary>
        /// Gets or Sets Circuit
        /// </summary>
        [DataMember(Name = "circuit", EmitDefaultValue = false)]
        public EaseeCoreDTOsSiteCircuitDTO Circuit { get; set; }

        /// <summary>
        /// Gets or Sets ChargerStates
        /// </summary>
        [DataMember(Name = "chargerStates", EmitDefaultValue = true)]
        public List<EaseeCoreDTOsDashboardDashboardChargerState> ChargerStates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsDashboardDashboardCircuitStateDTO {\n");
            sb.Append("  Circuit: ").Append(Circuit).Append("\n");
            sb.Append("  ChargerStates: ").Append(ChargerStates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsDashboardDashboardCircuitStateDTO);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsDashboardDashboardCircuitStateDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsDashboardDashboardCircuitStateDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsDashboardDashboardCircuitStateDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Circuit == input.Circuit ||
                    (this.Circuit != null &&
                    this.Circuit.Equals(input.Circuit))
                ) && 
                (
                    this.ChargerStates == input.ChargerStates ||
                    this.ChargerStates != null &&
                    input.ChargerStates != null &&
                    this.ChargerStates.SequenceEqual(input.ChargerStates)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Circuit != null)
                {
                    hashCode = (hashCode * 59) + this.Circuit.GetHashCode();
                }
                if (this.ChargerStates != null)
                {
                    hashCode = (hashCode * 59) + this.ChargerStates.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
