/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeAccessControlDomainDTOCircuitDTO
    /// </summary>
    [DataContract(Name = "Easee.AccessControl.Domain.DTO.CircuitDTO")]
    public partial class EaseeAccessControlDomainDTOCircuitDTO : IEquatable<EaseeAccessControlDomainDTOCircuitDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeAccessControlDomainDTOCircuitDTO" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="siteId">siteId.</param>
        /// <param name="circuitPanelId">circuitPanelId.</param>
        /// <param name="panelName">panelName.</param>
        /// <param name="ratedCurrent">ratedCurrent.</param>
        /// <param name="chargers">chargers.</param>
        /// <param name="masterBackplate">masterBackplate.</param>
        /// <param name="useDynamicMaster">useDynamicMaster.</param>
        /// <param name="parentCircuitId">parentCircuitId.</param>
        public EaseeAccessControlDomainDTOCircuitDTO(int id = default(int), int siteId = default(int), int circuitPanelId = default(int), string panelName = default(string), double ratedCurrent = default(double), List<EaseeAccessControlDomainDTOChargerDTO> chargers = default(List<EaseeAccessControlDomainDTOChargerDTO>), EaseeCoreDTOsMyProductsBackPlateDTO masterBackplate = default(EaseeCoreDTOsMyProductsBackPlateDTO), bool useDynamicMaster = default(bool), int? parentCircuitId = default(int?))
        {
            this.Id = id;
            this.SiteId = siteId;
            this.CircuitPanelId = circuitPanelId;
            this.PanelName = panelName;
            this.RatedCurrent = ratedCurrent;
            this.Chargers = chargers;
            this.MasterBackplate = masterBackplate;
            this.UseDynamicMaster = useDynamicMaster;
            this.ParentCircuitId = parentCircuitId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets SiteId
        /// </summary>
        [DataMember(Name = "siteId", EmitDefaultValue = false)]
        public int SiteId { get; set; }

        /// <summary>
        /// Gets or Sets CircuitPanelId
        /// </summary>
        [DataMember(Name = "circuitPanelId", EmitDefaultValue = false)]
        public int CircuitPanelId { get; set; }

        /// <summary>
        /// Gets or Sets PanelName
        /// </summary>
        [DataMember(Name = "panelName", EmitDefaultValue = true)]
        public string PanelName { get; set; }

        /// <summary>
        /// Gets or Sets RatedCurrent
        /// </summary>
        [DataMember(Name = "ratedCurrent", EmitDefaultValue = false)]
        public double RatedCurrent { get; set; }

        /// <summary>
        /// Gets or Sets Chargers
        /// </summary>
        [DataMember(Name = "chargers", EmitDefaultValue = true)]
        public List<EaseeAccessControlDomainDTOChargerDTO> Chargers { get; set; }

        /// <summary>
        /// Gets or Sets MasterBackplate
        /// </summary>
        [DataMember(Name = "masterBackplate", EmitDefaultValue = false)]
        public EaseeCoreDTOsMyProductsBackPlateDTO MasterBackplate { get; set; }

        /// <summary>
        /// Gets or Sets UseDynamicMaster
        /// </summary>
        [DataMember(Name = "useDynamicMaster", EmitDefaultValue = true)]
        public bool UseDynamicMaster { get; set; }

        /// <summary>
        /// Gets or Sets ParentCircuitId
        /// </summary>
        [DataMember(Name = "parentCircuitId", EmitDefaultValue = true)]
        public int? ParentCircuitId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeAccessControlDomainDTOCircuitDTO {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SiteId: ").Append(SiteId).Append("\n");
            sb.Append("  CircuitPanelId: ").Append(CircuitPanelId).Append("\n");
            sb.Append("  PanelName: ").Append(PanelName).Append("\n");
            sb.Append("  RatedCurrent: ").Append(RatedCurrent).Append("\n");
            sb.Append("  Chargers: ").Append(Chargers).Append("\n");
            sb.Append("  MasterBackplate: ").Append(MasterBackplate).Append("\n");
            sb.Append("  UseDynamicMaster: ").Append(UseDynamicMaster).Append("\n");
            sb.Append("  ParentCircuitId: ").Append(ParentCircuitId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeAccessControlDomainDTOCircuitDTO);
        }

        /// <summary>
        /// Returns true if EaseeAccessControlDomainDTOCircuitDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeAccessControlDomainDTOCircuitDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeAccessControlDomainDTOCircuitDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.SiteId == input.SiteId ||
                    this.SiteId.Equals(input.SiteId)
                ) && 
                (
                    this.CircuitPanelId == input.CircuitPanelId ||
                    this.CircuitPanelId.Equals(input.CircuitPanelId)
                ) && 
                (
                    this.PanelName == input.PanelName ||
                    (this.PanelName != null &&
                    this.PanelName.Equals(input.PanelName))
                ) && 
                (
                    this.RatedCurrent == input.RatedCurrent ||
                    this.RatedCurrent.Equals(input.RatedCurrent)
                ) && 
                (
                    this.Chargers == input.Chargers ||
                    this.Chargers != null &&
                    input.Chargers != null &&
                    this.Chargers.SequenceEqual(input.Chargers)
                ) && 
                (
                    this.MasterBackplate == input.MasterBackplate ||
                    (this.MasterBackplate != null &&
                    this.MasterBackplate.Equals(input.MasterBackplate))
                ) && 
                (
                    this.UseDynamicMaster == input.UseDynamicMaster ||
                    this.UseDynamicMaster.Equals(input.UseDynamicMaster)
                ) && 
                (
                    this.ParentCircuitId == input.ParentCircuitId ||
                    (this.ParentCircuitId != null &&
                    this.ParentCircuitId.Equals(input.ParentCircuitId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                hashCode = (hashCode * 59) + this.SiteId.GetHashCode();
                hashCode = (hashCode * 59) + this.CircuitPanelId.GetHashCode();
                if (this.PanelName != null)
                {
                    hashCode = (hashCode * 59) + this.PanelName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.RatedCurrent.GetHashCode();
                if (this.Chargers != null)
                {
                    hashCode = (hashCode * 59) + this.Chargers.GetHashCode();
                }
                if (this.MasterBackplate != null)
                {
                    hashCode = (hashCode * 59) + this.MasterBackplate.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.UseDynamicMaster.GetHashCode();
                if (this.ParentCircuitId != null)
                {
                    hashCode = (hashCode * 59) + this.ParentCircuitId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
