/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// Defines Easee.Core.Enums.SimplifiedChargerError
    /// </summary>
    public enum EaseeCoreEnumsSimplifiedChargerError
    {
        /// <summary>
        /// Enum NUMBER_100 for value: 100
        /// </summary>
        NUMBER_100 = 100,

        /// <summary>
        /// Enum NUMBER_103 for value: 103
        /// </summary>
        NUMBER_103 = 103,

        /// <summary>
        /// Enum NUMBER_106 for value: 106
        /// </summary>
        NUMBER_106 = 106,

        /// <summary>
        /// Enum NUMBER_107 for value: 107
        /// </summary>
        NUMBER_107 = 107,

        /// <summary>
        /// Enum NUMBER_108 for value: 108
        /// </summary>
        NUMBER_108 = 108,

        /// <summary>
        /// Enum NUMBER_109 for value: 109
        /// </summary>
        NUMBER_109 = 109,

        /// <summary>
        /// Enum NUMBER_110 for value: 110
        /// </summary>
        NUMBER_110 = 110,

        /// <summary>
        /// Enum NUMBER_111 for value: 111
        /// </summary>
        NUMBER_111 = 111,

        /// <summary>
        /// Enum NUMBER_113 for value: 113
        /// </summary>
        NUMBER_113 = 113,

        /// <summary>
        /// Enum NUMBER_207 for value: 207
        /// </summary>
        NUMBER_207 = 207,

        /// <summary>
        /// Enum NUMBER_218 for value: 218
        /// </summary>
        NUMBER_218 = 218

    }

}
