/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Equalizer.MaxAllocatedCurrentDTO")]
    public partial class EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO : IEquatable<EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO" /> class.
        /// </summary>
        /// <param name="maxCurrent">maxCurrent.</param>
        public EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO(int maxCurrent = default(int))
        {
            this.MaxCurrent = maxCurrent;
        }

        /// <summary>
        /// Gets or Sets MaxCurrent
        /// </summary>
        [DataMember(Name = "maxCurrent", EmitDefaultValue = false)]
        public int MaxCurrent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO {\n");
            sb.Append("  MaxCurrent: ").Append(MaxCurrent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MaxCurrent == input.MaxCurrent ||
                    this.MaxCurrent.Equals(input.MaxCurrent)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.MaxCurrent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
