/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.EaseeClient.Client.OpenAPIDateConverter;

namespace kern.services.EaseeClient.Model
{
    /// <summary>
    /// EaseeCoreDTOsDashboardDashboardStateDTO
    /// </summary>
    [DataContract(Name = "Easee.Core.DTOs.Dashboard.DashboardStateDTO")]
    public partial class EaseeCoreDTOsDashboardDashboardStateDTO : IEquatable<EaseeCoreDTOsDashboardDashboardStateDTO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EaseeCoreDTOsDashboardDashboardStateDTO" /> class.
        /// </summary>
        /// <param name="circuitStates">circuitStates.</param>
        /// <param name="site">site.</param>
        public EaseeCoreDTOsDashboardDashboardStateDTO(List<EaseeCoreDTOsDashboardDashboardCircuitStateDTO> circuitStates = default(List<EaseeCoreDTOsDashboardDashboardCircuitStateDTO>), EaseeCoreDTOsSiteSiteDTO site = default(EaseeCoreDTOsSiteSiteDTO))
        {
            this.CircuitStates = circuitStates;
            this.Site = site;
        }

        /// <summary>
        /// Gets or Sets CircuitStates
        /// </summary>
        [DataMember(Name = "circuitStates", EmitDefaultValue = true)]
        public List<EaseeCoreDTOsDashboardDashboardCircuitStateDTO> CircuitStates { get; set; }

        /// <summary>
        /// Gets or Sets Site
        /// </summary>
        [DataMember(Name = "site", EmitDefaultValue = false)]
        public EaseeCoreDTOsSiteSiteDTO Site { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EaseeCoreDTOsDashboardDashboardStateDTO {\n");
            sb.Append("  CircuitStates: ").Append(CircuitStates).Append("\n");
            sb.Append("  Site: ").Append(Site).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EaseeCoreDTOsDashboardDashboardStateDTO);
        }

        /// <summary>
        /// Returns true if EaseeCoreDTOsDashboardDashboardStateDTO instances are equal
        /// </summary>
        /// <param name="input">Instance of EaseeCoreDTOsDashboardDashboardStateDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EaseeCoreDTOsDashboardDashboardStateDTO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CircuitStates == input.CircuitStates ||
                    this.CircuitStates != null &&
                    input.CircuitStates != null &&
                    this.CircuitStates.SequenceEqual(input.CircuitStates)
                ) && 
                (
                    this.Site == input.Site ||
                    (this.Site != null &&
                    this.Site.Equals(input.Site))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CircuitStates != null)
                {
                    hashCode = (hashCode * 59) + this.CircuitStates.GetHashCode();
                }
                if (this.Site != null)
                {
                    hashCode = (hashCode * 59) + this.Site.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
