/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeServicesLifetimeEnergyReportingMeasurement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeServicesLifetimeEnergyReportingMeasurementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeServicesLifetimeEnergyReportingMeasurement
        //private EaseeServicesLifetimeEnergyReportingMeasurement instance;

        public EaseeServicesLifetimeEnergyReportingMeasurementTests()
        {
            // TODO uncomment below to create an instance of EaseeServicesLifetimeEnergyReportingMeasurement
            //instance = new EaseeServicesLifetimeEnergyReportingMeasurement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeServicesLifetimeEnergyReportingMeasurement
        /// </summary>
        [Fact]
        public void EaseeServicesLifetimeEnergyReportingMeasurementInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeServicesLifetimeEnergyReportingMeasurement
            //Assert.IsType<EaseeServicesLifetimeEnergyReportingMeasurement>(instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'MeasuredAt'
        /// </summary>
        [Fact]
        public void MeasuredAtTest()
        {
            // TODO unit test for the property 'MeasuredAt'
        }

    }

}
