/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsSiteSiteCostDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsSiteSiteCostDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsSiteSiteCostDTO
        //private EaseeCoreDTOsSiteSiteCostDTO instance;

        public EaseeCoreDTOsSiteSiteCostDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsSiteSiteCostDTO
            //instance = new EaseeCoreDTOsSiteSiteCostDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsSiteSiteCostDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsSiteSiteCostDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsSiteSiteCostDTO
            //Assert.IsType<EaseeCoreDTOsSiteSiteCostDTO>(instance);
        }


        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }
        /// <summary>
        /// Test the property 'CostPerKWh'
        /// </summary>
        [Fact]
        public void CostPerKWhTest()
        {
            // TODO unit test for the property 'CostPerKWh'
        }
        /// <summary>
        /// Test the property 'CostPerKwhExcludeVat'
        /// </summary>
        [Fact]
        public void CostPerKwhExcludeVatTest()
        {
            // TODO unit test for the property 'CostPerKwhExcludeVat'
        }
        /// <summary>
        /// Test the property 'Vat'
        /// </summary>
        [Fact]
        public void VatTest()
        {
            // TODO unit test for the property 'Vat'
        }

    }

}
