/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO
        //private EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO instance;

        public EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO
            //instance = new EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO
            //Assert.IsType<EaseeCoreDTOsScheduleWeeklyChargeScheduleRequestDTO>(instance);
        }


        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'Days'
        /// </summary>
        [Fact]
        public void DaysTest()
        {
            // TODO unit test for the property 'Days'
        }

    }

}
