/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsSessionAggregatedUsageDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsSessionAggregatedUsageDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsSessionAggregatedUsageDTO
        //private EaseeCoreDTOsSessionAggregatedUsageDTO instance;

        public EaseeCoreDTOsSessionAggregatedUsageDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsSessionAggregatedUsageDTO
            //instance = new EaseeCoreDTOsSessionAggregatedUsageDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsSessionAggregatedUsageDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsSessionAggregatedUsageDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsSessionAggregatedUsageDTO
            //Assert.IsType<EaseeCoreDTOsSessionAggregatedUsageDTO>(instance);
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'TotalEnergy'
        /// </summary>
        [Fact]
        public void TotalEnergyTest()
        {
            // TODO unit test for the property 'TotalEnergy'
        }

    }

}
