/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsSessionChargingSessionDetailDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsSessionChargingSessionDetailDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsSessionChargingSessionDetailDTO
        //private EaseeCoreDTOsSessionChargingSessionDetailDTO instance;

        public EaseeCoreDTOsSessionChargingSessionDetailDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsSessionChargingSessionDetailDTO
            //instance = new EaseeCoreDTOsSessionChargingSessionDetailDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsSessionChargingSessionDetailDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsSessionChargingSessionDetailDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsSessionChargingSessionDetailDTO
            //Assert.IsType<EaseeCoreDTOsSessionChargingSessionDetailDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ChargerId'
        /// </summary>
        [Fact]
        public void ChargerIdTest()
        {
            // TODO unit test for the property 'ChargerId'
        }
        /// <summary>
        /// Test the property 'ChargerName'
        /// </summary>
        [Fact]
        public void ChargerNameTest()
        {
            // TODO unit test for the property 'ChargerName'
        }
        /// <summary>
        /// Test the property 'TotalEnergyUsage'
        /// </summary>
        [Fact]
        public void TotalEnergyUsageTest()
        {
            // TODO unit test for the property 'TotalEnergyUsage'
        }
        /// <summary>
        /// Test the property 'TotalCost'
        /// </summary>
        [Fact]
        public void TotalCostTest()
        {
            // TODO unit test for the property 'TotalCost'
        }
        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Fact]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }

    }

}
