/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsChargerChargerDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsChargerChargerDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsChargerChargerDTO
        //private EaseeCoreDTOsChargerChargerDTO instance;

        public EaseeCoreDTOsChargerChargerDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsChargerChargerDTO
            //instance = new EaseeCoreDTOsChargerChargerDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsChargerChargerDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsChargerChargerDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsChargerChargerDTO
            //Assert.IsType<EaseeCoreDTOsChargerChargerDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Fact]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }
        /// <summary>
        /// Test the property 'BackPlate'
        /// </summary>
        [Fact]
        public void BackPlateTest()
        {
            // TODO unit test for the property 'BackPlate'
        }
        /// <summary>
        /// Test the property 'LevelOfAccess'
        /// </summary>
        [Fact]
        public void LevelOfAccessTest()
        {
            // TODO unit test for the property 'LevelOfAccess'
        }
        /// <summary>
        /// Test the property 'ProductCode'
        /// </summary>
        [Fact]
        public void ProductCodeTest()
        {
            // TODO unit test for the property 'ProductCode'
        }

    }

}
