/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsDashboardDashboardStateDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsDashboardDashboardStateDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsDashboardDashboardStateDTO
        //private EaseeCoreDTOsDashboardDashboardStateDTO instance;

        public EaseeCoreDTOsDashboardDashboardStateDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsDashboardDashboardStateDTO
            //instance = new EaseeCoreDTOsDashboardDashboardStateDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsDashboardDashboardStateDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsDashboardDashboardStateDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsDashboardDashboardStateDTO
            //Assert.IsType<EaseeCoreDTOsDashboardDashboardStateDTO>(instance);
        }


        /// <summary>
        /// Test the property 'CircuitStates'
        /// </summary>
        [Fact]
        public void CircuitStatesTest()
        {
            // TODO unit test for the property 'CircuitStates'
        }
        /// <summary>
        /// Test the property 'Site'
        /// </summary>
        [Fact]
        public void SiteTest()
        {
            // TODO unit test for the property 'Site'
        }

    }

}
