/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO
        //private EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO instance;

        public EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO
            //instance = new EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO
            //Assert.IsType<EaseeCoreDTOsEqualizerMaxAllocatedCurrentDTO>(instance);
        }


        /// <summary>
        /// Test the property 'MaxCurrent'
        /// </summary>
        [Fact]
        public void MaxCurrentTest()
        {
            // TODO unit test for the property 'MaxCurrent'
        }

    }

}
