/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreModelsSiteCurrency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreModelsSiteCurrencyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreModelsSiteCurrency
        //private EaseeCoreModelsSiteCurrency instance;

        public EaseeCoreModelsSiteCurrencyTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreModelsSiteCurrency
            //instance = new EaseeCoreModelsSiteCurrency();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreModelsSiteCurrency
        /// </summary>
        [Fact]
        public void EaseeCoreModelsSiteCurrencyInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreModelsSiteCurrency
            //Assert.IsType<EaseeCoreModelsSiteCurrency>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CountryId'
        /// </summary>
        [Fact]
        public void CountryIdTest()
        {
            // TODO unit test for the property 'CountryId'
        }

    }

}
