/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsChargerChargePlanDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsChargerChargePlanDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsChargerChargePlanDTO
        //private EaseeCoreDTOsChargerChargePlanDTO instance;

        public EaseeCoreDTOsChargerChargePlanDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsChargerChargePlanDTO
            //instance = new EaseeCoreDTOsChargerChargePlanDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsChargerChargePlanDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsChargerChargePlanDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsChargerChargePlanDTO
            //Assert.IsType<EaseeCoreDTOsChargerChargePlanDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ChargeStartTime'
        /// </summary>
        [Fact]
        public void ChargeStartTimeTest()
        {
            // TODO unit test for the property 'ChargeStartTime'
        }
        /// <summary>
        /// Test the property 'ChargeStopTime'
        /// </summary>
        [Fact]
        public void ChargeStopTimeTest()
        {
            // TODO unit test for the property 'ChargeStopTime'
        }
        /// <summary>
        /// Test the property 'Repeat'
        /// </summary>
        [Fact]
        public void RepeatTest()
        {
            // TODO unit test for the property 'Repeat'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Fact]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'ChargingCurrentLimit'
        /// </summary>
        [Fact]
        public void ChargingCurrentLimitTest()
        {
            // TODO unit test for the property 'ChargingCurrentLimit'
        }

    }

}
