/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsEqualizerMeterSettingsDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsEqualizerMeterSettingsDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsEqualizerMeterSettingsDTO
        //private EaseeCoreDTOsEqualizerMeterSettingsDTO instance;

        public EaseeCoreDTOsEqualizerMeterSettingsDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsEqualizerMeterSettingsDTO
            //instance = new EaseeCoreDTOsEqualizerMeterSettingsDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsEqualizerMeterSettingsDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsEqualizerMeterSettingsDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsEqualizerMeterSettingsDTO
            //Assert.IsType<EaseeCoreDTOsEqualizerMeterSettingsDTO>(instance);
        }


        /// <summary>
        /// Test the property 'DeviceMode'
        /// </summary>
        [Fact]
        public void DeviceModeTest()
        {
            // TODO unit test for the property 'DeviceMode'
        }
        /// <summary>
        /// Test the property 'ExternalMeterType'
        /// </summary>
        [Fact]
        public void ExternalMeterTypeTest()
        {
            // TODO unit test for the property 'ExternalMeterType'
        }

    }

}
