/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsDashboardDashboardCircuitStateDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsDashboardDashboardCircuitStateDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsDashboardDashboardCircuitStateDTO
        //private EaseeCoreDTOsDashboardDashboardCircuitStateDTO instance;

        public EaseeCoreDTOsDashboardDashboardCircuitStateDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsDashboardDashboardCircuitStateDTO
            //instance = new EaseeCoreDTOsDashboardDashboardCircuitStateDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsDashboardDashboardCircuitStateDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsDashboardDashboardCircuitStateDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsDashboardDashboardCircuitStateDTO
            //Assert.IsType<EaseeCoreDTOsDashboardDashboardCircuitStateDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Circuit'
        /// </summary>
        [Fact]
        public void CircuitTest()
        {
            // TODO unit test for the property 'Circuit'
        }
        /// <summary>
        /// Test the property 'ChargerStates'
        /// </summary>
        [Fact]
        public void ChargerStatesTest()
        {
            // TODO unit test for the property 'ChargerStates'
        }

    }

}
