/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeAccessControlModelsSitePermissionRequestDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeAccessControlModelsSitePermissionRequestDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeAccessControlModelsSitePermissionRequestDTO
        //private EaseeAccessControlModelsSitePermissionRequestDTO instance;

        public EaseeAccessControlModelsSitePermissionRequestDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeAccessControlModelsSitePermissionRequestDTO
            //instance = new EaseeAccessControlModelsSitePermissionRequestDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeAccessControlModelsSitePermissionRequestDTO
        /// </summary>
        [Fact]
        public void EaseeAccessControlModelsSitePermissionRequestDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeAccessControlModelsSitePermissionRequestDTO
            //Assert.IsType<EaseeAccessControlModelsSitePermissionRequestDTO>(instance);
        }


        /// <summary>
        /// Test the property 'PhoneNo'
        /// </summary>
        [Fact]
        public void PhoneNoTest()
        {
            // TODO unit test for the property 'PhoneNo'
        }
        /// <summary>
        /// Test the property 'SiteUserRole'
        /// </summary>
        [Fact]
        public void SiteUserRoleTest()
        {
            // TODO unit test for the property 'SiteUserRole'
        }

    }

}
