/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsSiteDynamicCircuitCurrentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsSiteDynamicCircuitCurrentDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsSiteDynamicCircuitCurrentDto
        //private EaseeCoreDTOsSiteDynamicCircuitCurrentDto instance;

        public EaseeCoreDTOsSiteDynamicCircuitCurrentDtoTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsSiteDynamicCircuitCurrentDto
            //instance = new EaseeCoreDTOsSiteDynamicCircuitCurrentDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsSiteDynamicCircuitCurrentDto
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsSiteDynamicCircuitCurrentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsSiteDynamicCircuitCurrentDto
            //Assert.IsType<EaseeCoreDTOsSiteDynamicCircuitCurrentDto>(instance);
        }


        /// <summary>
        /// Test the property 'Phase1'
        /// </summary>
        [Fact]
        public void Phase1Test()
        {
            // TODO unit test for the property 'Phase1'
        }
        /// <summary>
        /// Test the property 'Phase2'
        /// </summary>
        [Fact]
        public void Phase2Test()
        {
            // TODO unit test for the property 'Phase2'
        }
        /// <summary>
        /// Test the property 'Phase3'
        /// </summary>
        [Fact]
        public void Phase3Test()
        {
            // TODO unit test for the property 'Phase3'
        }

    }

}
