/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsCommandsCommandResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsCommandsCommandResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsCommandsCommandResponseDto
        //private EaseeCoreDTOsCommandsCommandResponseDto instance;

        public EaseeCoreDTOsCommandsCommandResponseDtoTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsCommandsCommandResponseDto
            //instance = new EaseeCoreDTOsCommandsCommandResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsCommandsCommandResponseDto
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsCommandsCommandResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsCommandsCommandResponseDto
            //Assert.IsType<EaseeCoreDTOsCommandsCommandResponseDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'DeliveredAt'
        /// </summary>
        [Fact]
        public void DeliveredAtTest()
        {
            // TODO unit test for the property 'DeliveredAt'
        }
        /// <summary>
        /// Test the property 'WasAccepted'
        /// </summary>
        [Fact]
        public void WasAcceptedTest()
        {
            // TODO unit test for the property 'WasAccepted'
        }
        /// <summary>
        /// Test the property 'ResultCode'
        /// </summary>
        [Fact]
        public void ResultCodeTest()
        {
            // TODO unit test for the property 'ResultCode'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Fact]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'Ticks'
        /// </summary>
        [Fact]
        public void TicksTest()
        {
            // TODO unit test for the property 'Ticks'
        }

    }

}
