/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeUserAdministrationDomainDTOSiteUserDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeUserAdministrationDomainDTOSiteUserDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeUserAdministrationDomainDTOSiteUserDTO
        //private EaseeUserAdministrationDomainDTOSiteUserDTO instance;

        public EaseeUserAdministrationDomainDTOSiteUserDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeUserAdministrationDomainDTOSiteUserDTO
            //instance = new EaseeUserAdministrationDomainDTOSiteUserDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeUserAdministrationDomainDTOSiteUserDTO
        /// </summary>
        [Fact]
        public void EaseeUserAdministrationDomainDTOSiteUserDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeUserAdministrationDomainDTOSiteUserDTO
            //Assert.IsType<EaseeUserAdministrationDomainDTOSiteUserDTO>(instance);
        }


        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'UserRole'
        /// </summary>
        [Fact]
        public void UserRoleTest()
        {
            // TODO unit test for the property 'UserRole'
        }

    }

}
