/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsSiteUpdateCircuitDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsSiteUpdateCircuitDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsSiteUpdateCircuitDTO
        //private EaseeCoreDTOsSiteUpdateCircuitDTO instance;

        public EaseeCoreDTOsSiteUpdateCircuitDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsSiteUpdateCircuitDTO
            //instance = new EaseeCoreDTOsSiteUpdateCircuitDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsSiteUpdateCircuitDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsSiteUpdateCircuitDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsSiteUpdateCircuitDTO
            //Assert.IsType<EaseeCoreDTOsSiteUpdateCircuitDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }
        /// <summary>
        /// Test the property 'CircuitPanelId'
        /// </summary>
        [Fact]
        public void CircuitPanelIdTest()
        {
            // TODO unit test for the property 'CircuitPanelId'
        }
        /// <summary>
        /// Test the property 'PanelName'
        /// </summary>
        [Fact]
        public void PanelNameTest()
        {
            // TODO unit test for the property 'PanelName'
        }
        /// <summary>
        /// Test the property 'RatedCurrent'
        /// </summary>
        [Fact]
        public void RatedCurrentTest()
        {
            // TODO unit test for the property 'RatedCurrent'
        }
        /// <summary>
        /// Test the property 'Backplates'
        /// </summary>
        [Fact]
        public void BackplatesTest()
        {
            // TODO unit test for the property 'Backplates'
        }

    }

}
