/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeAccessControlModelsRefreshTokenDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeAccessControlModelsRefreshTokenDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeAccessControlModelsRefreshTokenDTO
        //private EaseeAccessControlModelsRefreshTokenDTO instance;

        public EaseeAccessControlModelsRefreshTokenDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeAccessControlModelsRefreshTokenDTO
            //instance = new EaseeAccessControlModelsRefreshTokenDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeAccessControlModelsRefreshTokenDTO
        /// </summary>
        [Fact]
        public void EaseeAccessControlModelsRefreshTokenDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeAccessControlModelsRefreshTokenDTO
            //Assert.IsType<EaseeAccessControlModelsRefreshTokenDTO>(instance);
        }


        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }
        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Fact]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }

    }

}
