/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsEqualizerEqualizerConfigurationDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsEqualizerEqualizerConfigurationDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsEqualizerEqualizerConfigurationDTO
        //private EaseeCoreDTOsEqualizerEqualizerConfigurationDTO instance;

        public EaseeCoreDTOsEqualizerEqualizerConfigurationDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsEqualizerEqualizerConfigurationDTO
            //instance = new EaseeCoreDTOsEqualizerEqualizerConfigurationDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsEqualizerEqualizerConfigurationDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsEqualizerEqualizerConfigurationDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsEqualizerEqualizerConfigurationDTO
            //Assert.IsType<EaseeCoreDTOsEqualizerEqualizerConfigurationDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Ssid'
        /// </summary>
        [Fact]
        public void SsidTest()
        {
            // TODO unit test for the property 'Ssid'
        }
        /// <summary>
        /// Test the property 'EqualizerId'
        /// </summary>
        [Fact]
        public void EqualizerIdTest()
        {
            // TODO unit test for the property 'EqualizerId'
        }
        /// <summary>
        /// Test the property 'MasterBackPlateId'
        /// </summary>
        [Fact]
        public void MasterBackPlateIdTest()
        {
            // TODO unit test for the property 'MasterBackPlateId'
        }
        /// <summary>
        /// Test the property 'SiteStructure'
        /// </summary>
        [Fact]
        public void SiteStructureTest()
        {
            // TODO unit test for the property 'SiteStructure'
        }
        /// <summary>
        /// Test the property 'MeterId'
        /// </summary>
        [Fact]
        public void MeterIdTest()
        {
            // TODO unit test for the property 'MeterId'
        }
        /// <summary>
        /// Test the property 'MeterType'
        /// </summary>
        [Fact]
        public void MeterTypeTest()
        {
            // TODO unit test for the property 'MeterType'
        }
        /// <summary>
        /// Test the property 'ExternalMeterType'
        /// </summary>
        [Fact]
        public void ExternalMeterTypeTest()
        {
            // TODO unit test for the property 'ExternalMeterType'
        }
        /// <summary>
        /// Test the property 'GridType'
        /// </summary>
        [Fact]
        public void GridTypeTest()
        {
            // TODO unit test for the property 'GridType'
        }
        /// <summary>
        /// Test the property 'NumPhases'
        /// </summary>
        [Fact]
        public void NumPhasesTest()
        {
            // TODO unit test for the property 'NumPhases'
        }
        /// <summary>
        /// Test the property 'MaxAllocatedCurrent'
        /// </summary>
        [Fact]
        public void MaxAllocatedCurrentTest()
        {
            // TODO unit test for the property 'MaxAllocatedCurrent'
        }
        /// <summary>
        /// Test the property 'ChildReport'
        /// </summary>
        [Fact]
        public void ChildReportTest()
        {
            // TODO unit test for the property 'ChildReport'
        }
        /// <summary>
        /// Test the property 'DeviceMode'
        /// </summary>
        [Fact]
        public void DeviceModeTest()
        {
            // TODO unit test for the property 'DeviceMode'
        }

    }

}
