/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsChargerChargerEnergyDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsChargerChargerEnergyDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsChargerChargerEnergyDTO
        //private EaseeCoreDTOsChargerChargerEnergyDTO instance;

        public EaseeCoreDTOsChargerChargerEnergyDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsChargerChargerEnergyDTO
            //instance = new EaseeCoreDTOsChargerChargerEnergyDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsChargerChargerEnergyDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsChargerChargerEnergyDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsChargerChargerEnergyDTO
            //Assert.IsType<EaseeCoreDTOsChargerChargerEnergyDTO>(instance);
        }


        /// <summary>
        /// Test the property 'ChargerId'
        /// </summary>
        [Fact]
        public void ChargerIdTest()
        {
            // TODO unit test for the property 'ChargerId'
        }
        /// <summary>
        /// Test the property 'LifeTimeEnergy'
        /// </summary>
        [Fact]
        public void LifeTimeEnergyTest()
        {
            // TODO unit test for the property 'LifeTimeEnergy'
        }

    }

}
