/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeCoreDTOsSiteCircuitSettingsDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeCoreDTOsSiteCircuitSettingsDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeCoreDTOsSiteCircuitSettingsDTO
        //private EaseeCoreDTOsSiteCircuitSettingsDTO instance;

        public EaseeCoreDTOsSiteCircuitSettingsDTOTests()
        {
            // TODO uncomment below to create an instance of EaseeCoreDTOsSiteCircuitSettingsDTO
            //instance = new EaseeCoreDTOsSiteCircuitSettingsDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeCoreDTOsSiteCircuitSettingsDTO
        /// </summary>
        [Fact]
        public void EaseeCoreDTOsSiteCircuitSettingsDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeCoreDTOsSiteCircuitSettingsDTO
            //Assert.IsType<EaseeCoreDTOsSiteCircuitSettingsDTO>(instance);
        }


        /// <summary>
        /// Test the property 'MasterChargerId'
        /// </summary>
        [Fact]
        public void MasterChargerIdTest()
        {
            // TODO unit test for the property 'MasterChargerId'
        }
        /// <summary>
        /// Test the property 'DynamicCircuitCurrentP1'
        /// </summary>
        [Fact]
        public void DynamicCircuitCurrentP1Test()
        {
            // TODO unit test for the property 'DynamicCircuitCurrentP1'
        }
        /// <summary>
        /// Test the property 'DynamicCircuitCurrentP2'
        /// </summary>
        [Fact]
        public void DynamicCircuitCurrentP2Test()
        {
            // TODO unit test for the property 'DynamicCircuitCurrentP2'
        }
        /// <summary>
        /// Test the property 'DynamicCircuitCurrentP3'
        /// </summary>
        [Fact]
        public void DynamicCircuitCurrentP3Test()
        {
            // TODO unit test for the property 'DynamicCircuitCurrentP3'
        }
        /// <summary>
        /// Test the property 'MaxCircuitCurrentP1'
        /// </summary>
        [Fact]
        public void MaxCircuitCurrentP1Test()
        {
            // TODO unit test for the property 'MaxCircuitCurrentP1'
        }
        /// <summary>
        /// Test the property 'MaxCircuitCurrentP2'
        /// </summary>
        [Fact]
        public void MaxCircuitCurrentP2Test()
        {
            // TODO unit test for the property 'MaxCircuitCurrentP2'
        }
        /// <summary>
        /// Test the property 'MaxCircuitCurrentP3'
        /// </summary>
        [Fact]
        public void MaxCircuitCurrentP3Test()
        {
            // TODO unit test for the property 'MaxCircuitCurrentP3'
        }
        /// <summary>
        /// Test the property 'EnableIdleCurrent'
        /// </summary>
        [Fact]
        public void EnableIdleCurrentTest()
        {
            // TODO unit test for the property 'EnableIdleCurrent'
        }
        /// <summary>
        /// Test the property 'OfflineMaxCircuitCurrentP1'
        /// </summary>
        [Fact]
        public void OfflineMaxCircuitCurrentP1Test()
        {
            // TODO unit test for the property 'OfflineMaxCircuitCurrentP1'
        }
        /// <summary>
        /// Test the property 'OfflineMaxCircuitCurrentP2'
        /// </summary>
        [Fact]
        public void OfflineMaxCircuitCurrentP2Test()
        {
            // TODO unit test for the property 'OfflineMaxCircuitCurrentP2'
        }
        /// <summary>
        /// Test the property 'OfflineMaxCircuitCurrentP3'
        /// </summary>
        [Fact]
        public void OfflineMaxCircuitCurrentP3Test()
        {
            // TODO unit test for the property 'OfflineMaxCircuitCurrentP3'
        }

    }

}
