/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeBusinessLayerManagersTotalConsumptionSiteConsumption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeBusinessLayerManagersTotalConsumptionSiteConsumptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeBusinessLayerManagersTotalConsumptionSiteConsumption
        //private EaseeBusinessLayerManagersTotalConsumptionSiteConsumption instance;

        public EaseeBusinessLayerManagersTotalConsumptionSiteConsumptionTests()
        {
            // TODO uncomment below to create an instance of EaseeBusinessLayerManagersTotalConsumptionSiteConsumption
            //instance = new EaseeBusinessLayerManagersTotalConsumptionSiteConsumption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeBusinessLayerManagersTotalConsumptionSiteConsumption
        /// </summary>
        [Fact]
        public void EaseeBusinessLayerManagersTotalConsumptionSiteConsumptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeBusinessLayerManagersTotalConsumptionSiteConsumption
            //Assert.IsType<EaseeBusinessLayerManagersTotalConsumptionSiteConsumption>(instance);
        }


        /// <summary>
        /// Test the property 'SiteId'
        /// </summary>
        [Fact]
        public void SiteIdTest()
        {
            // TODO unit test for the property 'SiteId'
        }
        /// <summary>
        /// Test the property 'ChargerConsumption'
        /// </summary>
        [Fact]
        public void ChargerConsumptionTest()
        {
            // TODO unit test for the property 'ChargerConsumption'
        }

    }

}
