/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeSiteStructureDomainPortsBackPlateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeSiteStructureDomainPortsBackPlateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeSiteStructureDomainPortsBackPlateDto
        //private EaseeSiteStructureDomainPortsBackPlateDto instance;

        public EaseeSiteStructureDomainPortsBackPlateDtoTests()
        {
            // TODO uncomment below to create an instance of EaseeSiteStructureDomainPortsBackPlateDto
            //instance = new EaseeSiteStructureDomainPortsBackPlateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeSiteStructureDomainPortsBackPlateDto
        /// </summary>
        [Fact]
        public void EaseeSiteStructureDomainPortsBackPlateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeSiteStructureDomainPortsBackPlateDto
            //Assert.IsType<EaseeSiteStructureDomainPortsBackPlateDto>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MasterBackPlateId'
        /// </summary>
        [Fact]
        public void MasterBackPlateIdTest()
        {
            // TODO unit test for the property 'MasterBackPlateId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

    }

}
