/*
 * Easee Cloud API
 *
 * Find more information and documentation at <br/> <a href='https://developer.easee.cloud'>https://developer.easee.cloud</a>
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.EaseeClient.Api;
using kern.services.EaseeClient.Model;
using kern.services.EaseeClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.EaseeClient.Test.Model
{
    /// <summary>
    ///  Class for testing EaseeBusinessLayerManagersTotalConsumptionPeriod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EaseeBusinessLayerManagersTotalConsumptionPeriodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EaseeBusinessLayerManagersTotalConsumptionPeriod
        //private EaseeBusinessLayerManagersTotalConsumptionPeriod instance;

        public EaseeBusinessLayerManagersTotalConsumptionPeriodTests()
        {
            // TODO uncomment below to create an instance of EaseeBusinessLayerManagersTotalConsumptionPeriod
            //instance = new EaseeBusinessLayerManagersTotalConsumptionPeriod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EaseeBusinessLayerManagersTotalConsumptionPeriod
        /// </summary>
        [Fact]
        public void EaseeBusinessLayerManagersTotalConsumptionPeriodInstanceTest()
        {
            // TODO uncomment below to test "IsType" EaseeBusinessLayerManagersTotalConsumptionPeriod
            //Assert.IsType<EaseeBusinessLayerManagersTotalConsumptionPeriod>(instance);
        }


        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }

    }

}
